### ISSUE TITLE
Renaming generator?

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-xh#207]
Following Piotrek's question in #206 do you think we need to change generator's name to something like generator-xf after XHTMLized rebranding to Xfive? If so, what it takes to change the name of npm module?

Something's here http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module

**Comment by piotrkulpinski** [comment]
I guess that's up to people in Xfive to decide if they want to update their packages so maybe we should run a quick survey whether they want to update it. As for me, I don't think it's necessary but that's a question to our operations team if they want to keep the tools closely associated with brand name.
