### ISSUE TITLE
Disallow editing WP templates

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-xh#210]
Update `wp-config.php` template to include: 
`define('DISALLOW_FILE_EDIT', true);`
`define('DISALLOW_FILE_MODS', true);`

**Comment by luboskmetko** [comment]
Hey guys,

do you think this option should be set to true by default? What if this is forgotten, the site is moved to the client's server and they won't be able to install plugins as they want?

**Comment by piotrkulpinski** [comment]
I don't think this will disallow them to install new plugins.
It will only disable direct file edition using Administration > Appearance > Editor

**Comment by luboskmetko** [comment]
For me `DISALLOW_FILE_EDIT` removed _Add new_ on plugins page and when accessing wp-admin/plugin-install.php, I got _You do not have sufficient permissions to access this page._ Can you confirm if this happens to you too?

**Comment by piotrkulpinski** [comment]
@luboskmetko You're right, the "Add new plugin" button disappears when you add that.
However, if we need to only disallow file edition it's sufficient to leave only: `define('DISALLOW_FILE_EDIT', true);` which disabled file editor while still allow to add new plugins.

**Comment by ajgon** [comment]
What we can do is to use an environmental/server variable which will be set on previewized, but won't be used by client, i.e.

```php
define('DISALLOW_FILE_EDIT', !!$_SERVER['DISABLE_EDIT']);
define('DISALLOW_FILE_MODS', !!$_SERVER['DISABLE_EDIT']);
```

**Comment by luboskmetko** [comment]
@ajgon this sounds good, can you let me know when it's implemented at previewized so I can update the generator? Thanks

**Comment by ajgon** [comment]
Done on previewized.
